{'name': 'QA Application',
 'description': 'Question And Answer',
 'author': 'Nguyen Minh Man',
 'depends': [
     'base',
     'mail',
     'website_livechat',
     'website_forum',
     'backend_theme_v13',
     'auth_oauth',
     'google_calendar',
     'google_drive',
     'auth_signup',
     'document_page_procedure',
     'document_page_work_instruction',
     'document_page_quality_manual',

 ],
 'data': [
     'views/utc2_menu.xml',
     'views/qa_view.xml',
     'views/utc2_qa_category_view.xml',
     'views/res_config_settings_views.xml',
     'views/website_templates.xml',
     'views/portal_templates.xml',
     'views/assets.xml',
     'views/forum.xml',
     'views/website_livechat.xml',
     'views/website_profile.xml',
     'views/gamification_karma_rank_views.xml',
     'views/website_homepage.xml',
     'views/website_forum.xml',
     'views/res_users_views.xml',
     'security/utc2_security.xml',
     'security/ir.model.access.csv',
     'data/res_users_data.xml',
     'data/im_livechat_data.xml',
     'data/ir_default_data.xml',
     'data/website_data.xml',
     'data/gamification_data.xml',
     'data/auth_oauth_data.xml',
     'data/auth_signup_data.xml',
     'data/res_config_settings.xml',
     'data/mail.xml',
     'data/profile_data.xml',
     'data/forum_data.xml',
 ],

 'application': True,
 'installable': True,
 }
